
---
title: "Python y R compartiendo información"
author: "Pedro Luque"
date: "2022-09-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


```{r}
library(reticulate)
```


```{python}
import pandas
flights=pandas.read_csv("flights.csv")
flights=flights[flights['Dest']=="TPA"]
flights=flights[['CarrierDelay','DepDelay', 'ArrDelay']]
flights=flights.dropna()
```


"reticulate" crea el objeto "py" en R para que podamos acceder a los objetos creados en python.


```{r fig.width=7, fig.height=3}
library(ggplot2)
ggplot(py$flights, aes(CarrierDelay, ArrDelay)) + geom_point() + geom_jitter()
```





```{python}
# The standard way to import NumPy:
import numpy as np

# Create a 2-D array, set every second element in
# some rows and find max per row:

x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
x
# array([[  0,   1,   2,   3,   4],
#        [-99,   6, -99,   8, -99],
#        [-99,  11, -99,  13, -99]])

x.max(axis=1)
# array([ 4,  8, 13])

# Generate normally distributed random numbers:
rng = np.random.default_rng()
samples = rng.normal(size=2500)
samples
```




```{r}
py$samples
```
